apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s --volumes hostPath convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: ordering-backgroundtasks
  name: ordering-backgroundtasks
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ordering-backgroundtasks
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s --volumes hostPath convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: ordering-backgroundtasks
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:80
            - name: ApplicationInsights__InstrumentationKey
            - name: AzureServiceBusEnabled
              value: "False"
            - name: CheckUpdateTime
              value: "30000"
            - name: ConnectionString
              value: Server=docker.for.mac.localhost,5433;Database=Microsoft.eShopOnContainers.Services.OrderingDb;User Id=sa;Password=Pass@word
            - name: EventBusConnection
              value: docker.for.mac.localhost
            - name: EventBusPassword
            - name: EventBusUserName
            - name: GracePeriodTime
              value: "1"
            - name: OrchestratorType
            - name: Serilog__MinimumLevel__Override__Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ
              value: Verbose
            - name: UseCustomizationData
              value: "True"
            - name: UseLoadTest
              value: "False"
          image: eshop/ordering.backgroundtasks:linux-latest
          name: ordering-backgroundtasks
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
