apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s --volumes hostPath convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: seq
  name: seq
spec:
  ports:
    - name: "5340"
      port: 5340
      targetPort: 80
  selector:
    io.kompose.service: seq
status:
  loadBalancer: {}
