apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s --volumes hostPath convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: sqldata-tcp
  name: sqldata-tcp
spec:
  ports:
    - name: "5433"
      port: 5433
      targetPort: 1433
  selector:
    io.kompose.service: sqldata
  type: LoadBalancer
status:
  loadBalancer: {}
