apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s --volumes hostPath convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: webspa
  name: webspa
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webspa
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s --volumes hostPath convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: webspa
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:80
            - name: ApplicationInsights__InstrumentationKey
            - name: IdentityUrl
              value: http://docker.for.mac.localhost:5105
            - name: IdentityUrlHC
              value: http://identity-api/hc
            - name: OrchestratorType
            - name: PurchaseUrl
              value: http://docker.for.mac.localhost:5202
            - name: SignalrHubUrl
              value: http://docker.for.mac.localhost:5202
            - name: UseCustomizationData
              value: "True"
          image: eshop/webspa:linux-latest
          name: webspa
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
