apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -f docker-compose.override.yml -o k8s --volumes hostPath convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: webshoppingagg-tcp
  name: webshoppingagg-tcp
spec:
  ports:
    - name: "5121"
      port: 5121
      targetPort: 80
  selector:
    io.kompose.service: webshoppingagg
  type: LoadBalancer
status:
  loadBalancer: {}
